### ISSUE TITLE
Why can't see noises nodes in SG outputs?

### ISSUE THREAD

**Issue by ShockWave2048** [keijiro/ShaderGraphAssets#2]
Hi Keijiro!
Why can't see noises in SG outputs (editor, scene)? (Unity 2022.1.0b4.2571)
Thaks for answer!
![Screenshot_2](https://user-images.githubusercontent.com/800625/150633432-e40915dd-9683-4d57-acaf-2a16c1e95ac8.jpg)

**Comment by keijiro** [comment]
Because you're giving a constant input (0, 0). Obviously, the return value must be constant.

I'd recommend giving a varying input, like UV or Position.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
